//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Vize_Projesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Idare
    {
        public int idareid { get; set; }
        public string idareAdSoyad { get; set; }
        public string idareUnvan { get; set; }
        public Nullable<System.DateTime> idarebasla { get; set; }
        public Nullable<System.DateTime> idarecikis { get; set; }
    }
}
