//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Vize_Projesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ogretmen
    {
        public int ogretmenid { get; set; }
        public string OgretmenAd { get; set; }
        public string OgretmenSoyad { get; set; }
        public Nullable<System.DateTime> OgretmenGiris { get; set; }
        public Nullable<System.DateTime> OgretmenCikis { get; set; }
    }
}
