//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Vize_Projesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ogrenci
    {
        public int ogreinciid { get; set; }
        public string OgrenciBolum { get; set; }
        public string OgrenciAdSoyad { get; set; }
        public Nullable<int> OgrenciNo { get; set; }
        public Nullable<int> OgrenciKredi { get; set; }
        public Nullable<bool> OgrenciMezun { get; set; }
    }
}
